name: Build Docker Images
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/video-mitm
      - name: Build and release Docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          target: video-mitm
          tags: ${{ steps.metadata.outputs.tags }}
          push: true
